FROM golang:1.24.6

# current working directory
WORKDIR /simple-rest

# Download Go modules
COPY go.mod ./
RUN go mod download

# copy all the source code into the image
COPY *.go ./

# compile the application
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping

EXPOSE 10000

# tells docker what to run
CMD [ "/docker-gs-ping" ]